

//Static ClassName Defination
module.exports={
	
acfe:"-webkit-align-content: flex-end;-ms-flex-line-pack: end;align-content: flex-end",//
acfs:"-webkit-align-content: flex-start;-ms-flex-line-pack: start;align-content: flex-start",
acsa:"-webkit-align-content: space-around;-ms-flex-line-pack: distribute;align-content: space-around",
acsb:"-webkit-align-content: space-between;-ms-flex-line-pack: justify;align-content: space-between",
acs:"-webkit-align-content: stretch;-ms-flex-line-pack: stretch;align-content: stretch",
adar:"-webkit-animation-direction: alternate-reverse;animation-direction: alternate-reverse",
ada:"-webkit-animation-direction: alternate;animation-direction: alternate",
adnl:"-webkit-animation-direction: normal;animation-direction: normal",
adn:"-webkit-animation-direction: normal;animation-direction: normal",
adr:"-webkit-animation-direction: reverse;animation-direction: reverse",
afmb:"-webkit-animation-fill-mode: backwards;animation-fill-mode: backwards",
afmbo:"-webkit-animation-fill-mode: both;animation-fill-mode: both",
afmb2:"-webkit-animation-fill-mode: both;animation-fill-mode: both",
afmf:"-webkit-animation-fill-mode: forwards;animation-fill-mode: forwards",
afmn:"-webkit-animation-fill-mode: none;animation-fill-mode: none",
aib:"-webkit-align-items: baseline;-ms-flex-align: baseline;align-items: baseline",
aici:"-webkit-animation-iteration-count: infinite;animation-iteration-count: infinite",
aic:"-webkit-align-items: center;-ms-flex-align: center;align-items: center",
aife:"-webkit-align-items: flex-end;-ms-flex-align: end;align-items: flex-end",
aifs:"-webkit-align-items: flex-start;-ms-flex-align: start;align-items: flex-start",
ain:"all: inherit",
ais:"-webkit-align-items: stretch;-ms-flex-align: stretch;align-items: stretch",
ai:"all: initial",
ann:"-webkit-animation-name: none;animation-name: none",
apsp:"-webkit-animation-play-state: paused;animation-play-state: paused",
apsr:"-webkit-animation-play-state: running;animation-play-state: running",
asa:"-webkit-align-self: auto;-ms-flex-item-align: auto;align-self: auto",
asb:"-webkit-align-self: baseline;-ms-flex-item-align: baseline;align-self: baseline",
asc:"-webkit-align-self: center;-ms-flex-item-align: center;align-self: center",
asfe:"-webkit-align-self: flex-end;-ms-flex-item-align: end;align-self: flex-end",
asfs:"-webkit-align-self: flex-start;-ms-flex-item-align: start;align-self: flex-start",
ass:"-webkit-align-self: stretch;-ms-flex-item-align: stretch;align-self: stretch",
atfeio:"-webkit-animation-timing-function: ease-in-out;animation-timing-function: ease-in-out",
atfei:"-webkit-animation-timing-function: ease-in;animation-timing-function: ease-in",
atfeo:"-webkit-animation-timing-function: ease-out;animation-timing-function: ease-out",
atfe:"-webkit-animation-timing-function: ease;animation-timing-function: ease",
atfl:"-webkit-animation-timing-function: linear;animation-timing-function: linear",
atfse:"-webkit-animation-timing-function: step-end;animation-timing-function: step-end",
atfss:"-webkit-animation-timing-function: step-start;animation-timing-function: step-start",
au:"all: unset",
b0:"border:0",
baac:"-webkit-column-break-after: avoid-column;page-break-after: avoid-column;break-after: avoid-column",

baf:"box-align: after",
baal:"-webkit-column-break-after: always;page-break-after: always;break-after: always",
baa3:"-webkit-column-break-after: always;page-break-after: always;break-after: always",
baap:"-webkit-column-break-after: avoid;page-break-after: avoid;break-after: avoid-page",
baa:"-webkit-column-break-after: auto;page-break-after: auto;break-after: auto",
baav:"-webkit-column-break-after: avoid;page-break-after: avoid;break-after: avoid",
baa2:"-webkit-column-break-after: avoid;page-break-after: avoid;break-after: avoid",
babl:"box-align: baseline",
bab2:"box-align: baseline",
bab:"box-align: before",
bac:"-webkit-column-break-after: column;page-break-after: column;break-after: column",
bal:"-webkit-column-break-after: left;page-break-after: left;break-after: left",
bam:"box-align: middle",
bap:"-webkit-column-break-after: page;page-break-after: page;break-after: page",
bar:"-webkit-column-break-after: right;page-break-after: right;break-after: right",
btma:"bottom: auto",
ba:"bottom: auto",
bas:"box-align: stretch",
bbac:"-webkit-column-break-before: avoid-column;page-break-before: avoid-column;break-before: avoid-column",
bbal:"-webkit-column-break-before: always;page-break-before: always;break-before: always",
bba3:"-webkit-column-break-before: always;page-break-before: always;break-before: always",
bbap:"-webkit-column-break-before: avoid;page-break-before: avoid;break-before: avoid-page",
bba:"-webkit-column-break-before: auto;page-break-before: auto;break-before: auto",
bbav:"-webkit-column-break-before: avoid;page-break-before: avoid;break-before: avoid",
bba2:"-webkit-column-break-before: avoid;page-break-before: avoid;break-before: avoid",
bbc_t:"border-bottom-color: transparent",
bbct:"border-bottom-color: transparent",
bbcn:"border-bottom-color:none",
bbcin:"border-bottom: inherit",
bbc_in:"border-bottom: inherit",
bbc:"-webkit-column-break-before: column;page-break-before: column;break-before: column",
bbl:"-webkit-column-break-before: left;page-break-before: left;break-before: left",
bbp:"-webkit-column-break-before: page;page-break-before: page;break-before: page",
bbr:"-webkit-column-break-before: right;page-break-before: right;break-before: right",
bbsdb:"border-bottom-style: double",
bbsds:"border-bottom-style: dashed",
bbsdt:"border-bottom-style: dotted",
bbsd2:"border-bottom-style: double",
bbsd:"border-bottom-style: dashed",
bbsd3:"border-bottom-style: dotted",
bbsg:"border-bottom-style: groove",
bbsh:"border-bottom-style: hidden",
bbsi:"border-bottom-style: inset",
bbsn:"border-bottom-style: none",
bbso:"border-bottom-style: outset",
bbsr:"border-bottom-style: ridge",
bbss:"border-bottom-style: solid",
bbwm:"border-bottom-width: medium",
bbwt:"border-bottom-width: thick",
bbwtn:"border-bottom-width: thin",
bbwt2:"border-bottom-width: thin",//------------
bc_t:"border-color: transparent",
bct:"border-color: transparent",
bcin:"border-color: inherit",
bcn2:"border-color: inherit",
bc_in:"border-color: inherit",
bcn:"border-color:none",
bcc:"border-collapse: collapse",
bcs:"border-collapse: separate",
bdbc:"-webkit-box-decoration-break: clone;box-decoration-break: clone",
bdbs:"-webkit-box-decoration-break: slice;box-decoration-break: slice",
bgaf:"background-attachment: fixed",
bgal:"background-attachment: local",
bgas:"background-attachment: scroll",
bgcbb:"background-clip: border-box",
bgccb:"background-clip: content-box",
bgcin:"background-color:inherit",
bgc_in:"background-color:inherit",
bgcpb:"background-clip: padding-box",
bgct:"background-color: transparent",
bgt:"background: transparent",
bgn:"background:none",
bgcn:"background-color:none",
bgc_t:"background-color: transparent",
bgin:"background-image: none",
bgobb:"background-origin: border-box",
bgocb:"background-origin: content-box",
bgoin:"background-origin: inherit",
bgopb:"background-origin: padding-box",
bgpc:"background-position: center center",
bgpl:"background-position: left top",
bgpr:"background-position: right bottom",
bgrn:"background-repeat: no-repeat",
bgrnr:"background-repeat: no-repeat",
bgrrn:"background-repeat: repeat no-repeat",
bgrrnr:"background-repeat: repeat no-repeat",
bgpct:"background-position: center center",
bgplt:"background-position: left top",
bgprb:"background-position: right bottom",
bgnr:"background-repeat: no-repeat",
bgrnr:"background-repeat: repeat no-repeat",
bgrr:"background-repeat: repeat",
bgrro:"background-repeat: round",
bgrs:"background-repeat: space",
bgrx:"background-repeat: repeat-x",
bgrrx:"background-repeat: repeat-x",
bgry:"background-repeat: repeat-y",
bgrry:"background-repeat: repeat-y",
bgsa:"background-size: auto",
bgscon:"background-size: contain",
bgsc:"background-size: cover",
biac:"-webkit-column-break-inside: avoid;page-break-inside: avoid;break-inside: avoid-column",
biap:"page-break-inside: avoid;break-inside: avoid-page",
bia:"-webkit-column-break-inside: auto;page-break-inside: auto;break-inside: auto",
biav:"-webkit-column-break-inside: avoid;page-break-inside: avoid;break-inside: avoid",
bia2:"-webkit-column-break-inside: avoid;page-break-inside: avoid;break-inside: avoid",
birro:"border-image-repeat: round",
birr:"border-image-repeat: repeat",
bir2:"border-image-repeat: repeat",//--------------
birsth:"border-image-repeat: stretch",
birs2:"border-image-repeat: stretch",
birs:"border-image-repeat: space",
bisn:"border-image-source: none",
blc_t:"border-left-color: transparent",
blct:"border-left-color: transparent",
blcn:"border-left-color: none",
blsdb:"border-left-style: double",
blsds:"border-left-style: dashed",
blsdt:"border-left-style: dotted",
blsd2:"border-left-style: double",//------------
blsd:"border-left-style: dashed",
blsd3:"border-left-style: dotted",
blsg:"border-left-style: groove",
blsh:"border-left-style: hidden",
blsi:"border-left-style: inset",
blsn:"border-left-style: none",
blso:"border-left-style: outset",
blsr:"border-left-style: ridge",
blss:"border-left-style: solid",
blwm:"border-left-width: medium",
blwt:"border-left-width: thick",
blwtn:"border-left-width: thin",
blwt2:"border-left-width: thin",
bn:"border:none",
bbn:"border-bottom:none",
brn:"border-right:none",
btno:"border-top:none",//conflict with bootrap
bln:"border-left:none",
brcn:"border-right-color: none",
brc_t:"border-right-color: transparent",
brct:"border-right-color: transparent",
brsdb:"border-right-style: double",
brsds:"border-right-style: dashed",
brsdt:"border-right-style: dotted",
brsd2:"border-right-style: double",//-----------------
brsd:"border-right-style: dashed",
brsd3:"border-right-style: dotted",
brsg:"border-right-style: groove",
brsh:"border-right-style: hidden",
brsi:"border-right-style: inset",
brsn:"border-right-style: none",
brso:"border-right-style: outset",
brsr:"border-right-style: ridge",
brss:"border-right-style: solid",
brwm:"border-right-width: medium",
brwt:"border-right-width: thick",
brwtn:"border-right-width: thin",
brwt2:"border-right-width: thin",
bsbb:"box-sizing: border-box",
bscb:"box-sizing: content-box",
bsdb:"border-style: double",
bsds:"border-style: dashed",
bsdt:"border-style: dotted",
bsd2:"border-style: double",//--------------
bsd:"border-style: dashed",
bsd3:"border-style: dotted",
bsg:"border-style: groove",
bsh:"border-style: hidden",
bsi:"border-style: inset",
bsn:"border-style: none",
bxsn:"box-shadow: none",
bso:"border-style: outset",
bspb:"box-sizing: padding-box",
bspb:"box-sizing: padding-box",
bsr:"border-style: ridge",
bss:"border-style: solid",
btc_t:"border-top-color: transparent",
btct:"border-top-color: transparent",
btcn:"border-top-color: none",
btsdb:"border-top-style: double",
btsds:"border-top-style: dashed",
btsdt:"border-top-style: dotted",
btsd2:"border-top-style: double",
btsd:"border-top-style: dashed",
btsd3:"border-top-style: dotted",
btsg:"border-top-style: groove",
btsh:"border-top-style: hidden",
btsi:"border-top-style: inset",
btsn:"border-top-style: none",
btso:"border-top-style: outset",
btsr:"border-top-style: ridge",
btss:"border-top-style: solid",
btwm:"border-top-width: medium",
btwt:"border-top-width: thick",
btwtn:"border-top-width: thin",
btwt2:"border-top-width: thin",//------------------
bvh:"-webkit-backface-visibility: hidden;backface-visibility: hidden",
bvv:"-webkit-backface-visibility: visible;backface-visibility: visible",
bwm:"border-width: medium",
bwt:"border-width: thick",
bwtn:"border-width: thin",
bwt2:"border-width: thin",
ccc:"color:currentColor",
cc:"color:currentColor",//-------------
c_cc:"color:currentColor",
c_in:"color:inherit",
ci:"color:inherit",
cab:"clear-after: both",
cabtm:"clear-after: bottom",
cab2:"clear-after: bottom",
cad:"clear-after: descendants",
cae:"clear-after: end",
cai:"clear-after: inside",
cal:"clear-after: left",
can:"clear-after: none",
cao:"clear-after: outside",
car:"clear-after: right",
cast:"clear-after: start",
cas2:"clear-after: start",
cas:"cursor: all-scroll",
cat:"clear-after: top",
cla:"clip: auto",
ca3:"clip: auto",
cal:"cursor: alias",
ca2:"cursor: alias",
ca:"cursor: auto",
cb:"clear: both",
cca:"-webkit-column-count: auto;-moz-column-count: auto;column-count: auto",
cch:"cursor: crosshair",
ccl:"cursor: cell",
ccm:"cursor: context-menu",
concq:"content: close-quote",
ccr:"cursor: col-resize",
cc:"cursor: copy",
cd:"cursor: default",
cer:"cursor: e-resize",
cewr:"cursor: ew-resize",
cfa:"-webkit-column-fill: auto;-moz-column-fill: auto;column-fill: auto",
cfb:"-webkit-column-fill: balance;-moz-column-fill: balance;column-fill: balance",
cgnl:"-webkit-column-gap: normal;-moz-column-gap: normal;column-gap: normal",
ch:"cursor: help",
ciin:"counter-increment: inherit",
cii:"counter-increment: inherit",
cili:"counter-increment: list-item",
cin:"counter-increment: none",
coni:"content: icon",
ci2:"content: icon",//-------------------------
cl:"clear: left",
cm:"cursor: move",
cna:"cursor: not-allowed",
conncq:"content: no-close-quote",
cncq:"content: no-close-quote",
cnd:"cursor: no-drop",
cner:"cursor: ne-resize",
cnr8:"cursor: ne-resize",
cnr7:"cursor: ne-resize",
cneswr:"cursor: nesw-resize",
cnr6:"cursor: nesw-resize",
cnr5:"cursor: nesw-resize",
connl:"content: normal",
cn4:"content: normal",
connoq:"content: no-open-quote",
cnoq:"content: no-open-quote",
//cnrr:"cursor: n-resize",
cnsr:"cursor: ns-resize",
cnwr:"cursor: nw-resize",
cnwser:"cursor: nwse-resize",
cnr:"cursor: n-resize",
cnr2:"cursor: ns-resize",
cnr3:"cursor: nw-resize",
cnr4:"cursor: nwse-resize",
cn:"clear: none",
con:"content:\"\"",//-------------------
conn:"content: none",
cn3:"content: none",
cnone:"cursor: none",
cn2:"cursor: none",
coq:"content: open-quote",
cpg:"cursor: progress",
cp2:"cursor: progress",//-------------

cp:"cursor: pointer",
crin:"counter-reset: inherit",
cri:"counter-reset: inherit",
crli:"counter-reset: list-item",
crn:"counter-reset: none",
crr:"cursor: row-resize",
crsdb:"-webkit-column-rule-style: double;-moz-column-rule-style: double;column-rule-style: double",
crsd2:"-webkit-column-rule-style: double;-moz-column-rule-style: double;column-rule-style: double",
crsds:"-webkit-column-rule-style: dashed;-moz-column-rule-style: dashed;column-rule-style: dashed",
crsd:"-webkit-column-rule-style: dashed;-moz-column-rule-style: dashed;column-rule-style: dashed",
crsdt:"-webkit-column-rule-style: dotted;-moz-column-rule-style: dotted;column-rule-style: dotted",
crsd3:"-webkit-column-rule-style: dotted;-moz-column-rule-style: dotted;column-rule-style: dotted",
crsg:"-webkit-column-rule-style: groove;-moz-column-rule-style: groove;column-rule-style: groove",
crsh:"-webkit-column-rule-style: hidden;-moz-column-rule-style: hidden;column-rule-style: hidden",
crsi:"-webkit-column-rule-style: inset;-moz-column-rule-style: inset;column-rule-style: inset",
crsn:"-webkit-column-rule-style: none;-moz-column-rule-style: none;column-rule-style: none",
crso:"-webkit-column-rule-style: outset;-moz-column-rule-style: outset;column-rule-style: outset",
crsr:"-webkit-column-rule-style: ridge;-moz-column-rule-style: ridge;column-rule-style: ridge",
crss:"-webkit-column-rule-style: solid;-moz-column-rule-style: solid;column-rule-style: solid",
crwm:"-webkit-column-rule-width: medium;-moz-column-rule-width: medium;column-rule-width: medium",
crwt:"-webkit-column-rule-width: thick;-moz-column-rule-width: thick;column-rule-width: thick",
crwtn:"-webkit-column-rule-width: thin;-moz-column-rule-width: thin;column-rule-width: thin",
crwt2:"-webkit-column-rule-width: thin;-moz-column-rule-width: thin;column-rule-width: thin",
cr:"clear: right",
csa:"-webkit-column-span: all;-moz-column-span: all;column-span: all",
csbtm:"caption-side: bottom",
cser:"cursor: se-resize",
csr3:"cursor: se-resize",//--------------
csn:"-webkit-column-span: none;-moz-column-span: none;column-span: none",
csr:"cursor: s-resize",
cst:"caption-side: top",
cswr:"cursor: sw-resize",
csr2:"cursor: sw-resize",
c_t:"color:transparent",
ct2:"color:transparent",
ct:"cursor: text",
cvt:"cursor: vertical-text",
cwa:"-webkit-column-width: auto;-moz-column-width: auto;column-width: auto",
cwr:"cursor: w-resize",
cw:"cursor: wait",
czi:"cursor: -webkit-zoom-in;cursor: zoom-in",
czo:"cursor: -webkit-zoom-out;cursor: zoom-out",
db:"display: block",
dcp:"display: compact",
dc2:"display: compact",
dc:"display: container",
df:"display: -webkit-flex;display: -ms-flexbox;display: flex",
dib:"display: inline-block",
dif:"display: -webkit-inline-flex;display: -ms-inline-flexbox;display: inline-flex",
dit:"display: inline-table",
di:"display: inline",
dli:"display: list-item",
dn:"display: none",
dri:"display: run-in",
dtcg:"display: table-column-group",
dtcl:"display: table-cell",
dtc3:"display: table-cell",
dtcp:"display: table-caption",
dtc2:"display: table-caption",
dtc:"display: table-column",
dtfg:"display: table-footer-group",
dthg:"display: table-header-group",
dtrg:"display: table-row-group",
dtr:"display: table-row",
dt:"display: table",
ech:"empty-cells: hide",
ecs:"empty-cells: show",
fa:"-webkit-flex: auto;-ms-flex: auto;flex: auto",
fba:"-webkit-flex-basis: auto;-ms-flex-preferred-size: auto;flex-basis: auto",
fbc:"-webkit-flex-basis:content;-ms-flex-preferred-size:content;flex-basis:content",
fbin:"-webkit-flex-basis: inherit;-ms-flex-preferred-size: inherit;flex-basis: inherit",
ffc:"-webkit-flex-direction: column;-ms-flex-direction: column;flex-direction: column",
fdc:"-webkit-flex-direction: column;-ms-flex-direction: column;flex-direction: column",
ffcn:"-webkit-flex-flow: column nowrap;-ms-flex-flow: column nowrap;flex-flow: column nowrap",
ffcr:"-webkit-flex-direction: column-reverse;-ms-flex-direction: column-reverse;flex-direction: column-reverse",
fdcr:"-webkit-flex-direction: column-reverse;-ms-flex-direction: column-reverse;flex-direction: column-reverse",
ffcrn:"-webkit-flex-flow: column-reverse nowrap;-ms-flex-flow: column-reverse nowrap;flex-flow: column-reverse nowrap",
ffcrwr:"-webkit-flex-flow:column-reverse wrap-reverse;-ms-flex-flow:column-reverse wrap-reverse;flex-flow:column-reverse wrap-reverse",
ffcrw:"-webkit-flex-flow: column-reverse wrap;-ms-flex-flow: column-reverse wrap;flex-flow: column-reverse wrap",
ffcu:"font-family: cursive",
ffcwr:"-webkit-flex-flow: column wrap-reverse;-ms-flex-flow: column wrap-reverse;flex-flow: column wrap-reverse",
ffcw:"-webkit-flex-flow:column wrap;-ms-flex-flow:column wrap;flex-flow:column wrap",
fff:"font-family: fantasy",
ffin:"font-family: inherit",
ffin2:"font-family: initial",//-----------
ffi:"font-family: inherit",//---------
ffi2:"font-family:initial",
ffm:"font-family: monospace",
ffn:"-webkit-flex-wrap: nowrap;-ms-flex-wrap: nowrap;flex-wrap: nowrap",
fwn:"-webkit-flex-wrap: nowrap;-ms-flex-wrap: nowrap;flex-wrap: nowrap",
ffr:"-webkit-flex-direction: row;-ms-flex-direction: row;flex-direction: row",
fdr:"-webkit-flex-direction: row;-ms-flex-direction: row;flex-direction: row",
ffrn:"-webkit-flex-flow:row nowrap;-ms-flex-flow:row nowrap;flex-flow:row nowrap",
ffrr:"-webkit-flex-direction: row-reverse;-ms-flex-direction: row-reverse;flex-direction: row-reverse",
fdrr:"-webkit-flex-direction: row-reverse;-ms-flex-direction: row-reverse;flex-direction: row-reverse",
ffrrn:"-webkit-flex-flow: row-reverse nowrap;-ms-flex-flow: row-reverse nowrap;flex-flow: row-reverse nowrap",
ffrrwr:"-webkit-flex-flow: row-reverse wrap-reverse;-ms-flex-flow: row-reverse wrap-reverse;flex-flow: row-reverse wrap-reverse",
ffrrw:"-webkit-flex-flow:row-reverse wrap;-ms-flex-flow:row-reverse wrap;flex-flow:row-reverse wrap",
ffrwr:"-webkit-flex-flow:row wrap-reverse;-ms-flex-flow:row wrap-reverse;flex-flow:row wrap-reverse",
ffrw:"-webkit-flex-flow: row wrap;-ms-flex-flow: row wrap;flex-flow: row wrap",
ffss:"font-family: sans-serif",
ffs:"font-family: serif",
ffw:"-webkit-flex-flow-wrap: wrap;-ms-flex-flow-wrap: wrap;flex-flow-wrap: wrap",//flex-flow
fww:"-webkit-flex-wrap: wrap;-ms-flex-wrap: wrap;flex-wrap: wrap",
ffwp:"-webkit-flex-flow-wrap: wrap-reverse;-ms-flex-flow-wrap: wrap-reverse;flex-flow-wrap: wrap-reverse",
fwwr:"-webkit-flex-wrap: wrap-reverse;-ms-flex-wrap: wrap-reverse;flex-wrap: wrap-reverse",
fgin:"-webkit-flex-grow:inherit;-ms-flex-positive:inherit;flex-grow:inherit",
fgi:"-webkit-flex-grow:inherit;-ms-flex-positive:inherit;flex-grow:inherit",
fiaa:"flex-item-align: auto",
fiab:"flex-item-align: baseline",
fiac:"flex-item-align: center",
fiae:"flex-item-align: end",
fiasth:"flex-item-align: stretch",
fias2:"flex-item-align: stretch",
fias:"flex-item-align: start",
fi2:"-webkit-flex: initial;-ms-flex: initial;flex: initial",
fin:"font:inherit",
fi:"font:inherit",
fka:"-webkit-font-kerning: auto;font-kerning: auto",
fknl:"-webkit-font-kerning: normal;font-kerning: normal",
fkn2:"-webkit-font-kerning: normal;font-kerning: normal",
fkn:"-webkit-font-kerning: none;font-kerning: none",
flin:"filter: inherit",//-------------------
fli:"filter: initial",
flu:"filter: unset",
fi4:"filter: inherit",
fi3:"filter: initial",
fu:"filter: unset",
flpc:"flex-line-pack: center",
flpd:"flex-line-pack: distribute",
flpe:"flex-line-pack: end",
flpj:"flex-line-pack: justify",
flpsth:" flex-line-pack: stretch",
flps2:" flex-line-pack: stretch",
flps:"flex-line-pack: start",
fl:"float: left",
/*flex: none;*/
fn:"float: none",
fr:"float: right",
fsain:"font-size-adjust: inherit",
fsai:"font-size-adjust: inherit",//-------------
fsan:"font-size-adjust: none",
fsc:"font-stretch: condensed",
fsec:"font-stretch: extra-condensed",
fsee:"font-stretch: extra-expanded",
fse:"font-stretch: expanded",
fskin:"-webkit-flex-shrink:inherit;-ms-flex-negative:inherit;flex-shrink:inherit",
fsi3:"-webkit-flex-shrink:inherit;-ms-flex-negative:inherit;flex-shrink:inherit",
fsin:"font-size:inherit",
fsi2:"font-size:inherit",
fsi:"font-style: italic",
fslr:"font-size: larger",
fsl2:"font-size: larger",
fsl:"font-size: large",
fsm:"font-size: medium",
fsnml:"font-stretch: normal",
fsn3:"font-stretch: normal",//-----------------
fsnl:"font-style: normal",
fsn2:"font-style: normal",
fsn:"font-synthesis: none",
fso:"font-style: oblique",
fssc:"font-stretch: semi-condensed",
fsse:"font-stretch: semi-expanded",
fssr:"font-size: smaller",
fss2:"font-size: smaller",//-------------------
fss:"font-size: small",
/*font-synthesis: style;*/
fsuc:"font-stretch: ultra-condensed",
fsue:"font-stretch: ultra-expanded",
fsws:"font-synthesis: weight style",
fsw:"font-synthesis: weight",
fsxl:"font-size: x-large",
fsxs:"font-size: x-small",
fsxxl:"font-size: xx-large",
fsxl2:"font-size: xx-large",
fsxxs:"font-size: xx-small",
fsxs2:"font-size: xx-small",//------------
fvapc:"font-variant: all-petite-caps",
fvasc:"font-variant: all-small-caps",
fvcapc:"font-variant-caps: all-petite-caps",
fvcasc:"font-variant-caps: all-small-caps",
fvcn:"font-variant-caps: normal",//-----------------
fvcnl:"font-variant-caps: normal",
fvcpc:"font-variant-caps: petite-caps",
fvcsc:"font-variant-caps: small-caps",
fvctc:"font-variant-caps: titling-caps",
fvcu:"font-variant-caps: unicase",
fvnl:"font-variant: normal",
fvpc:"font-variant: petite-caps",
fvsc:"font-variant: small-caps",
fvtc:"font-variant: titling-caps",
fvu:"font-variant: unicase",
fw1:"font-weight: 100",
fw2:"font-weight: 200",
fw3:"font-weight: 300",
fw4:"font-weight: 400",
fw5:"font-weight: 500",
fw6:"font-weight: 600",
fw7:"font-weight: 700",
fw8:"font-weight: 800",
fw9:"font-weight: 900",
fwb:"font-weight: bold",
fwbr:"font-weight: bolder",
fwb2:"font-weight: bolder",
fwl:"font-weight: lighter",
fwnl:"font-weight: normal",
fwn:"font-weight: normal",
/*height: auto;*/
ha:"-webkit-hyphens: auto;-moz-hyphens: auto;-ms-hyphens: auto;hyphens: auto",
hm:"-webkit-hyphens: manual;-moz-hyphens: manual;-ms-hyphens: manual;hyphens: manual",
hn:"-webkit-hyphens: none;-moz-hyphens: none;-ms-hyphens: none;hyphens: none",
hpae:"hanging-punctuation: allow-end",
hpfae:"hanging-punctuation: first allow-end",
hpfe:"hanging-punctuation: force-end",
hpffe:"hanging-punctuation: first force-end",
hpf:"hanging-punctuation: first",
hplae:"hanging-punctuation: last allow-end",
hplfe:"hanging-punctuation: last force-end",
hpl:"hanging-punctuation: last",
hpn:"hanging-punctuation: none",
ia:"icon: auto",
iof:"image-orientation: flip",
ioin:"image-orientation: inherit",
ioi:"image-orientation: inherit",
jcc:"-webkit-justify-content: center;-ms-flex-pack: center;justify-content: center",
jcfe:"-webkit-justify-content: flex-end;-ms-flex-pack: end;justify-content: flex-end",
jcfs:"-webkit-justify-content: flex-start;-ms-flex-pack: start;justify-content: flex-start",
jcsa:"-webkit-justify-content: space-around;-ms-flex-pack: distribute;justify-content: space-around",
jcsb:"-webkit-justify-content: space-between;-ms-flex-pack: justify;justify-content: space-between",
la:"left: auto",
lba:"line-break: auto",
lbl:"line-break: loose",
lbnl:"line-break: normal",
lbn:"line-break: normal",//-----------------------------
lbs:"line-break: strict",
lhnl:"line-height: normal",
lhn:"line-height: normal",
lhin:"line-height:inherit",
lhi:"line-height:inherit",
lhi2:"line-height:initial",
lsa:"list-style-type: armenian",
lsta:"list-style-type: armenian",
lsc:"list-style-type: circle",
lstc:"list-style-type: circle",
lsd:"list-style-type: disc",
lstd:"list-style-type: disc",
lsdc:"list-style-type: decimal",
lsd2:"list-style-type: decimal",
lsdc:"list-style-type: decimal",
lstd2:"list-style-type: decimal",
lsdlz:"list-style-type: decimal-leading-zero",
lstdlz:"list-style-type: decimal-leading-zero",
lsg:"list-style-type: georgian",
lstg:"list-style-type: georgian",
lsin:"list-style-image: none",
lsla:"list-style-type: lower-alpha",
lstla:"list-style-type: lower-alpha",
lslg:"list-style-type: lower-greek",
lstlg:"list-style-type: lower-greek",
lsll:"list-style-type: lower-latin",
lstll:"list-style-type: lower-latin",
lslr:"list-style-type: lower-roman",
lstlr:"list-style-type: lower-roman",
lsn:"list-style: none",
lstn:"list-style-type: none",
lesnl:"letter-spacing: normal",//---------------
lsnl:"letter-spacing: normal",
lsn2:"letter-spacing: normal",
lspi:"list-style-position: inside",
lspo:"list-style-position: outside",
lss:"list-style-type: square",
lsts:"list-style-type: square",
lsua:"list-style-type: upper-alpha",
lstua:"list-style-type: upper-alpha",
lsul:"list-style-type: upper-latin",
lstul:"list-style-type: upper-latin",
lsur:"list-style-type: upper-roman",
lstur:"list-style-type: upper-roman",
mba:"margin-bottom: auto",
mha:"min-height: auto",
mla:"margin-left: auto",
mra:"margin-right: auto",
mta:"margin-top: auto",
mwa:"min-width: auto",
mwa:"min-width: auto",
o0:"opacity:0",
o10:"opacity:1",
o1:"opacity:0.1",
o2:"opacity:0.2",
o3:"opacity:0.3",
o4:"opacity:0.4",
o5:"opacity:0.5",
o6:"opacity:0.6",
o7:"opacity:0.7",
o8:"opacity:0.8",
o9:"opacity:0.9",
oa:"overflow: auto",
ol0:"outline:0",//--------------
oln:"outline:none",
olci:"outline-color: invert",
oci:"outline-color: invert",
oci2:"outline-color: inherit",

oct:"outline-color:transparent",
olct:"outline-color:transparent",
olc_t:"outline-color:transparent",
oc_t:"outline-color:transparent",

olc_in:"outline-color:inherit",
oc_in:"outline-color:inherit",
ofcon:"object-fit: contain",
ofc:"object-fit: cover",
off:"object-fit: fill",
ofn:"object-fit: none",
ofsd:"object-fit: scale-down",
oh:"overflow: hidden",
ooin:"outline-offset: inherit",
ooi:"outline-offset: inherit",

opcc:"object-position: center center",
oplt:"object-position: left top",
oprb:"object-position: right bottom",
ordin:"-webkit-order:inherit;-ms-flex-order:inherit;order:inherit",
orpin:"orphans: inherit",
osa:"outline-style: auto",
osdb:"outline-style: double",
osds:"outline-style: dashed",
osdt:"outline-style: dotted",
osd2:"outline-style: double",
osd:"outline-style: dashed",
osd3:"outline-style: dotted",//-------------
osg:"outline-style: groove",
osi:"outline-style: inset",
osn:"outline-style: none",
oso:"outline-style: outset",
osr:"outline-style: ridge",
oss:"outline-style: solid",
os:"overflow: scroll",
ov:"overflow: visible",
owbw:"overflow-wrap: break-word",
owm:"outline-width: medium",
ownl:"overflow-wrap: normal",
own:"overflow-wrap: normal",

owt:"outline-width: thick",
owtn:"outline-width: thin",//-------------------
owt2:"outline-width: thin",
owww:"overflow-wrap: word-wrap",
oxa:"overflow-x: auto",
oxh:"overflow-x: hidden",
oxs:"overflow-x: scroll",
oxv:"overflow-x: visible",
oya:"overflow-y: auto",
oyh:"overflow-y: hidden",
oys:"overflow-y: scroll",
oyv:"overflow-y: visible",
pa:"position: absolute",
pbaal:"page-break-after: always",
pbaa3:"page-break-after: always",
pbaav:"page-break-after: avoid",
pbaa2:"page-break-after: avoid",
pbaa:"page-break-after: auto",
pbal:"page-break-after: left",
pbar:"page-break-after: right",
pbbal:"page-break-before: always",
pbba3:"page-break-before: always",
pbbav:"page-break-before: avoid",
pbba2:"page-break-before: avoid",//--------------
pbba:"page-break-before: auto",
pbbl:"page-break-before: left",
pbbr:"page-break-before: right",
pbia:"page-break-inside: auto",
pbiav:"page-break-inside: avoid",
pbia2:"page-break-inside: avoid",
pc:"position: center",
pea:"pointer-events: auto",
pen:"pointer-events: none",
pf:"position: fixed",
pin:"-webkit-perspective: inherit;perspective: inherit",
pi:"-webkit-perspective: inherit;perspective: inherit",//--------------
pn:"-webkit-perspective: none;perspective: none",
pobl:"-webkit-perspective-origin: bottom left;perspective-origin: bottom left",
pobr:"-webkit-perspective-origin: bottom right;perspective-origin: bottom right",
pobtm:"-webkit-perspective-origin: bottom;perspective-origin: bottom",
pob:"-webkit-perspective-origin: bottom;perspective-origin: bottom",
poc:"-webkit-perspective-origin: center;perspective-origin: center",
poin:"-webkit-perspective-origin: inherit;perspective-origin: inherit",
poi:"-webkit-perspective-origin: inherit;perspective-origin: inherit",
pol:"-webkit-perspective-origin: left;perspective-origin: left",
por:"-webkit-perspective-origin: right;perspective-origin: right",
potl:"-webkit-perspective-origin: top left;perspective-origin: top left",
potr:"-webkit-perspective-origin: top right;perspective-origin: top right",
pot:"-webkit-perspective-origin: top;perspective-origin: top",
pp:"position: page",
pr:"position: relative",
ps:"position: static",
pst:"position: -webkit-sticky;position: sticky",
ps2:"position: -webkit-sticky;position: sticky",//-------------
qn:"quotes: none",
ra:"right: auto",
rb:"resize: both",
rh:"resize: horizontal",
rv:"resize: vertical",
tac:"text-align: center",
tae:"text-align: end",
taj:"text-align: justify",
tala:"-moz-text-align-last: auto;text-align-last: auto",
talc:"-moz-text-align-last: center;text-align-last: center",
tale:"-moz-text-align-last: end;text-align-last: end",
talj:"-moz-text-align-last: justify;text-align-last: justify",
tall:"-moz-text-align-last: left;text-align-last: left",
talr:"-moz-text-align-last: right;text-align-last: right",
tals:"-moz-text-align-last: start;text-align-last: start",
tal:"text-align: left",
tamp:"text-align: match-parent",
tar:"text-align: right",
tase:"text-align: start end",
tas:"text-align: start",
ta:"top: auto",
tcha:"text-combine-horizontal: all",
tchd:"text-combine-horizontal: digits ",
tchn:"text-combine-horizontal: none",
tdds:"text-decoration: dashed",
tdsds:"text-decoration: dashed",
tdd:"text-decoration: dashed",//-----------------------
tdsd:"text-decoration-style: dashed",
tdb:"text-decoration: blink",
tdlb:"text-decoration-line: blink",
tdc_in:"-webkit-text-decoration-color: inherit;text-decoration-color: inherit",
tdcin:"-webkit-text-decoration-color: inherit;text-decoration-color: inherit",
tdc_t:"-webkit-text-decoration-color: transparent;text-decoration-color: transparent",
tdct:"-webkit-text-decoration-color: transparent;text-decoration-color: transparent",
tddb:"text-decoration: double",
tdsdb:"text-decoration: double",
tddt:"text-decoration: dotted",
tdsdt:"text-decoration: dotted",
tdd2:"text-decoration: double",
tdsd2:"text-decoration-style: double",
tdd3:"text-decoration: dotted",
tdsd3:"text-decoration-style: dotted",
tdin:"text-decoration:inherit; ",
tdi:"text-decoration:inherit;",
tduin:"transition-duration: inherit",
tdui2:"transition-duration: inherit",
tdli:"transition-delay: initial",

tdlt:"text-decoration: line-through",
// tdllt:"text-decoration: line-through",
tdn:"text-decoration: none",
tdo:"text-decoration: overline",
tdlo:"text-decoration: overline",
tdsbd:"text-decoration-skip: box-decoration",
tdsdb:"-webkit-text-decoration-style: double;text-decoration-style: double",
tdsds:"-webkit-text-decoration-style: dashed;text-decoration-style: dashed",
tdsdt:"-webkit-text-decoration-style: dotted;text-decoration-style: dotted",
tdsd:"-webkit-text-decoration-style: double;text-decoration-style: double",
tdsd2:"-webkit-text-decoration-style: dashed;text-decoration-style: dashed",
tdsd3:"-webkit-text-decoration-style: dotted;text-decoration-style: dotted",
tdse:"text-decoration-skip: edges",
tdsi:"text-decoration-skip: ink",
tdsn:"text-decoration-skip: none",
tdso:"text-decoration-skip: objects",
tdssp:"text-decoration-skip: spaces",
tdss:"-webkit-text-decoration-style: solid;text-decoration-style: solid",
tdsw:"-webkit-text-decoration-style: wavy;text-decoration-style: wavy",
tdu:"text-decoration: underline",
tdlu:"text-decoration: underline",/*text-decoration-line*/
tdus:"text-decoration: unset",
tdw:"text-decoration: wavy",
//tdsw:"text-decoration: wavy",/*text-decoration-style*/repeat
tec_t:"text-emphasis-color:transparent ",
tect:"text-emphasis-color:transparent ",//------------
tepbl:"text-emphasis-position: below left",
tepbr:"text-emphasis-position: below right",
tepol:"text-emphasis-position: over left",
tepor:"text-emphasis-position: over right",
tesc:"text-emphasis-style: circle",
tesdc:"text-emphasis-style: double-circle",
tesd:"text-emphasis-style: dot",
tesf:"text-emphasis-style: filled",
tesn:"text-emphasis-style: none",
teso:"text-emphasis-style: open",
tess:"text-emphasis-style: sesame",
test:"text-emphasis-style: triangle",
tetep:"-webkit-text-emphasis: text-emphasis-position;text-emphasis: text-emphasis-position",
tiel:"text-indent: each-line",
tih:"text-indent: hanging",
tiin:"text-indent: inherit",
tii:"text-indent: inherit",
tja:"text-justify: auto",
tjd:"text-justify: distribute",
tjiw:"text-justify: inter-word",
tjn:"text-justify: none",
tla:"table-layout: auto",
tlf:"table-layout: fixed",
tn:"-webkit-transform: none;transform: none",
tobtm:"-webkit-transform-origin: bottom;transform-origin: bottom",
tob:"-webkit-transform-origin: bottom;transform-origin: bottom",//------------
tocl:"text-overflow: clip",
toc2:"text-overflow: clip",//----------------
toc:"-webkit-transform-origin: center;transform-origin: center",
toe:"text-overflow: ellipsis",
tol:"-webkit-transform-origin: left;transform-origin: left",
tom:"text-orientation: mixed",
tor:"-webkit-transform-origin: right;transform-origin: right",
tosl:"text-orientation: sideways-left",
tosr:"text-orientation: sideways-right",
tos:"text-orientation: sideways",
tot:"-webkit-transform-origin: top;transform-origin: top",
tougo:"text-orientation: use-glyph-orientation",
tou:"text-orientation: upright",
tpa:"transition-property: all",
tpn:"transition-property: none",
tra:"text-rendering: auto",
trgp:"text-rendering: geometricPrecision",
trg:"text-rendering: geometricPrecision",
trin:"text-rendering: inherit",
tri:"text-rendering: inherit",
trop:"text-rendering: optimizeLegibility",
tro:"text-rendering: optimizeLegibility",
tros:"text-rendering: optimizeSpeed",
tro2:"text-rendering: optimizeSpeed",
tsf:"-webkit-transform-style: flat;transform-style: flat",
tsi:"text-shadow: inherit",
tsin:"text-shadow: inherit",
tsi2:"-webkit-transform-style: inherit;transform-style: inherit",
tsin2:"-webkit-transform-style: inherit;transform-style: inherit",
tsn:"text-shadow: none",
tsp3d:"-webkit-transform-style: preserve-3d;transform-style: preserve-3d",
tsp3:"-webkit-transform-style: preserve-3d;transform-style: preserve-3d",
ttc:"text-transform: capitalize",
ttfeio:"transition-timing-function: ease-in-out",
ttfei:"transition-timing-function: ease-in",
ttfeo:"transition-timing-function: ease-out",
ttfe:"transition-timing-function: ease",
ttfl:"transition-timing-function: linear",
ttfse:"transition-timing-function: step-end",
ttfss:"transition-timing-function: step-start",
ttfw:"text-transform: full-width",
ttl:"text-transform: lowercase",
ttn:"text-transform: none",
ttu:"text-transform: uppercase",
tupa:"text-underline-position: auto",
tupl:"text-underline-position: left",
tupr:"text-underline-position: right",
tupul:"text-underline-position: under left",
tupur:"text-underline-position: under right",
tupu:"text-underline-position: under",
ubbo:"unicode-bidi: bidi-override",
ube:"unicode-bidi: embed",
ubnl:"unicode-bidi: normal",
ubn:"unicode-bidi: normal",
vab:"vertical-align: baseline",
vab2:"vertical-align: bottom",
vabtm:"vertical-align: bottom",//-----------------
vam:"vertical-align: middle",
vasb:"vertical-align: sub",//-----------------
vas:"vertical-align: super",
vatb:"vertical-align: text-bottom",
vatt:"vertical-align: text-top",
vat:"vertical-align: top",
vc:"visibility: collapse",
vh:"visibility: hidden",
vv:"visibility: visible",
wa:"width: auto",
wbba:"word-break: break-all",
wbka:"word-break: keep-all",
wbnl:"word-break: normal",
wbn:"word-break: normal",
wmht:"-webkit-writing-mode: horizontal-tb;-ms-writing-mode: lr-tb;writing-mode: horizontal-tb",
wmvl:"-webkit-writing-mode: vertical-lr;-ms-writing-mode: tb-lr;writing-mode: vertical-lr",
wmvr:"-webkit-writing-mode: vertical-rl;-ms-writing-mode: tb-rl;writing-mode: vertical-rl",
wsn:"white-space: nowrap",
wsnw:"white-space: nowarp",
wsnl:"white-space: normal",
wsn2:"white-space: normal",//---------
wosnl:"word-spacing: normal",
wsn3:"word-spacing:normal",//---------------
wspl:"white-space: pre-line",
wspw:"white-space: pre-wrap",
wsp:"white-space: pre",
wwbw:"word-wrap: break-word",
wwnl:"word-wrap: normal",
wwn:"word-wrap: normal",//-------------
wwow:"word-wrap: overflow-wrap",
xhn:"max-height: none",
xwn:"max-width: none",
zia:"z-index: auto",
};//endofstaticclassNames

//-----------------------------end of modal
